### ISSUE TITLE
Paging view bug

### ISSUE THREAD

**Issue by AngryShaDoW** [ByteNuts/NetCoreControls#4]
We have css  for "a" tag classes "active" and "disabled", but classes are aply for "li" elements. Problem is actual since beta-2. (At beta-1 all is ok )
![grid_bug_1](https://user-images.githubusercontent.com/3998455/40962142-5bd06028-68ad-11e8-98dd-fd14113b3376.png)
![grid_bug_2](https://user-images.githubusercontent.com/3998455/40962144-5dc8ffac-68ad-11e8-834e-5551567f51f6.png)
![grid_bug_3](https://user-images.githubusercontent.com/3998455/40962146-5f438910-68ad-11e8-9a54-909a107b8819.png)

**Comment by jrcpereira** [comment]
I've been traveling...
Sorry for the delay.

Thanks for the pull request!
